### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by calisroving** [qkleinfelter/portfolio-rewrite#1]
In /about, change RoiSys to RoviSys
![image](https://user-images.githubusercontent.com/89557378/236041559-2848cd47-acb6-4c1e-9d34-eda25a50d579.png)

**Comment by qkleinfelter** [comment]
Resolved in #[381f104](https://github.com/qkleinfelter/portfolio-rewrite/commit/381f104263755a2e2e4b75b5249173bf08fbcf3e) Thanks!
